USE [master]
GO

/****** Object:  Database [PinkFlamingos]    Script Date: 9/25/2016 12:47:34 PM ******/
CREATE DATABASE [PinkFlamingos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PinkFlamingos', FILENAME = N'C:\Users\Ruth\PinkFlamingos.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PinkFlamingos_log', FILENAME = N'C:\Users\Ruth\PinkFlamingos_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PinkFlamingos] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PinkFlamingos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PinkFlamingos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PinkFlamingos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PinkFlamingos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PinkFlamingos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PinkFlamingos] SET ARITHABORT OFF 
GO

ALTER DATABASE [PinkFlamingos] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PinkFlamingos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PinkFlamingos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PinkFlamingos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PinkFlamingos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PinkFlamingos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PinkFlamingos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PinkFlamingos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PinkFlamingos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PinkFlamingos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PinkFlamingos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PinkFlamingos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PinkFlamingos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PinkFlamingos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PinkFlamingos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PinkFlamingos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PinkFlamingos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PinkFlamingos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PinkFlamingos] SET  MULTI_USER 
GO

ALTER DATABASE [PinkFlamingos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PinkFlamingos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PinkFlamingos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PinkFlamingos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PinkFlamingos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PinkFlamingos] SET  READ_WRITE 
GO


