//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkFlamingoStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billingAddress
    {
        public int idBillingAdd { get; set; }
        public int idTransaction { get; set; }
        public int idUser { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public int zipCode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public int telephoneNumber { get; set; }
    }
}
