//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkFlamingoStudios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditCardInfo
    {
        public int idTransaction { get; set; }
        public int idUser { get; set; }
        public long creditCardNumber { get; set; }
        public string expDate { get; set; }
        public int cvc { get; set; }
        public string cardName { get; set; }
    }
}
